version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 --threads 2 -b 0.0.0.0:5000 run:app
    expose:
      - "5000"      # 内部暴露端口供 nginx 使用
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"     # 外部暴露端口
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
